services:
  - type: web
    name: file-share
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase_key.json
      - key: SECRET_KEY
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
